server:
  port: 8002
spring:
  application:
    name: mqPro
  rabbitmq:
    host: 159.75.126.247
    port: 5672
    username: xz
    password: 19950813
    virtual-host: TestHost
    #    确认消息已发送到队列
    publisher-returns: true
    #    确认消息已送到交换机
    publisher-confirm-type: correlated

